spring:
  application:
    name: KeelungSightsViewer
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
    disable-swagger-default-url: false
    tagsSorter: alpha
  default-produces-media-type: application/json