spring:
  application:
    name: KeelungSightsViewer
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password:
    url: 'jdbc:h2:mem:ksv'
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update  # 當 spring boot entity 有修改時, 會自動修改 DB scheam
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

server:
  address: 0.0.0.0
  port: 5050

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
    disable-swagger-default-url: false
    tagsSorter: alpha
  default-produces-media-type: application/json